INSERT INTO categories (name, icon_name, highlight_color) VALUES
('Жилье', 'home', 'ROYAL_BLUE'),
('Коммунальные услуги', 'droplet', 'AQUA_BLUE'),
('Связь и интернет', 'wifi', 'LAVENDER'),
('Одежда', 'shopping-bag', 'HOT_PINK'),
('Здоровье', 'heart', 'RUBY_RED'),
('Красота', 'smile', 'BUBBLEGUM_PINK'),
('Аптека', 'plus-circle', 'FIRE_ENGINE_RED'),
('Кафе и рестораны', 'coffee', 'SUNSET_ORANGE'),
('Кино и театры', 'film', 'AMETHYST'),
('Хобби', 'music', 'LAVENDER'),
('Путешествия', 'globe', 'EMERALD_GREEN'),
('Книги', 'book', 'COBALT_BLUE'),
('Сбережения', 'dollar-sign', 'GOLDEN_YELLOW'),
('Инвестиции', 'trending-up', 'ELECTRIC_GREEN'),
('Страхование', 'shield', 'SKY_BLUE'),
('Кредиты', 'credit-card', 'LILAC'),
('Зарплата', 'briefcase', 'MINT_GREEN'),
('Фриланс', 'edit', 'LEMON_YELLOW'),
('Подарки', 'gift', 'NEON_PINK'),
('Дивиденды', 'pie-chart', 'GOLDEN_YELLOW'),
('Образование', 'book-open', 'ROYAL_BLUE'),
('Дети', 'users', 'BUBBLEGUM_PINK'),
('Питомцы', 'github', 'SUNSET_ORANGE'),
('Благотворительность', 'hand-heart', 'RUBY_RED'),
('Неожиданные расходы', 'alert-circle', 'ASH_GRAY');