export const PortalHostName = {
	CREATE_NEW_TRANSACTION_BOTTOM_SHEET: "CREATE_NEW_TRANSACTION_BOTTOM_SHEET",
	FAST_ACTIONS_BOTTOM_SHEET: "FAST_ACTIONS_BOTTOM_SHEET",

	NEW_TRANSACTION_BOTTOM_SHEET: "NEW_TRANSACTION_BOTTOM_SHEET"
} as const;
